server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # WMS raster tiles  →  172.18.0.5:8080/geoserver/regional_dew/wms
    location /wms-proxy {
        proxy_pass http://172.18.0.5:8080/geoserver/regional_dew/wms;
        proxy_set_header Host 172.18.0.5;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # TMS vector tiles + WFS GeoJSON  →  172.18.1.168:8080/geoserver
    location /geo-proxy/ {
        rewrite ^/geo-proxy/(.*)$ /geoserver/$1 break;
        proxy_pass http://172.18.1.168:8080;
        proxy_set_header Host 172.18.1.168;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
