export const normalityCountriesList = [
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Guam",
    "4_result": "above normal",
    "5_result": "above normal",
    "6_result": "above normal",
    "7_result": "above normal",
    "8_result": "above normal",
    "9_result": "above normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Bangladesh",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "above normal",
    "7_result": "above normal",
    "8_result": "above normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Sierra Leone",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "above normal",
    "8_result": "above normal",
    "9_result": "above normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Bhutan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "above normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Myanmar",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Guinea-Bissau",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "above normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Nepal",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "Hong Kong",
    "4_result": "below normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Federated States of Micronesia",
    "4_result": "above normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Guinea",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Palau",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "Macau",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Liberia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Costa Rica",
    "4_result": "below normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Guatemala",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Nicaragua",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Guyana",
    "4_result": "below normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Laos",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Venezuela",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "South Korea",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Philippines",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "India",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Northern Mariana Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Cambodia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": null,
    "name": null,
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Colombia",
    "4_result": "above normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Panama",
    "4_result": "below normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "North Korea",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Vietnam",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Dominica",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Suriname",
    "4_result": "below normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Melanesia",
    "name": "Solomon Islands",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Thailand",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Marshall Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Melanesia",
    "name": "Papua New Guinea",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Brunei",
    "4_result": "below normal",
    "5_result": "above normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Nigeria",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Honduras",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Barbados",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Belize",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Central African Republic",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Saint Lucia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "Japan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Central America",
    "name": "Clipperton Island",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Tuvalu",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "El Salvador",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Trinidad and Tobago",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Benin",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Cameroon",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Nauru",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "The Gambia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Saint Vincent and the Grenadines",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Malaysia",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Burkina Faso",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Togo",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Grenada",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Liechtenstein",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Indonesia",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "South Sudan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Montserrat",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Ivory Coast",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Antigua and Barbuda",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Seven seas (open ocean)",
    "name": "British Indian Ocean Territory",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Micronesia",
    "name": "Kiribati",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Switzerland",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Ghana",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Puerto Rico",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Cayman Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Wallis and Futuna",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Saint Kitts and Nevis",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Seven seas (open ocean)",
    "name": "Australian Indian Ocean Territories",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "name": "New Zealand",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "Singapore",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Senegal",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "United States Virgin Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "American Samoa",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Samoa",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Jamaica",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Melanesia",
    "name": "Vanuatu",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Austria",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Cuba",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Ethiopia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Netherlands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "The Bahamas",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Southern Asia",
    "name": "Maldives",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Central America",
    "name": "Mexico",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Netherlands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "British Virgin Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Isle of Man",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "People's Republic of China",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Ecuador",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Saint Martin",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Sint Maarten",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Slovenia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Guantanamo Bay Naval Base",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Aruba",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Northern America",
    "name": "Bermuda",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Melanesia",
    "name": "New Caledonia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Haiti",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Slovakia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Dominican Republic",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Melanesia",
    "name": "Fiji",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Chad",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Anguilla",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Netherlands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Turks and Caicos Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Niue",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Seven seas (open ocean)",
    "name": "Australian Indian Ocean Territories",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Seven seas (open ocean)",
    "name": "South Georgia and the South Sandwich Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Cook Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Pitcairn Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Eastern Africa",
    "name": "Mauritius",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Czech Republic",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Saint-Barthélemy",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Faroe Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Poland",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": null,
    "subregion": null,
    "name": null,
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Germany",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Sweden",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Northern America",
    "name": "Saint Pierre and Miquelon",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Netherlands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Mali",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Uruguay",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Equatorial Guinea",
    "4_result": "above normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "Tonga",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Chile",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Seven seas (open ocean)",
    "name": "French Southern and Antarctic Lands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Sri Lanka",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Eastern Africa",
    "name": "Seychelles",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Ireland",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Belarus",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Romania",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Bosnia and Herzegovina",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "United Kingdom",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Seven seas (open ocean)",
    "name": "Heard Island and McDonald Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Lithuania",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Belgium",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Norway",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Denmark",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Finland",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Luxembourg",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Estonia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Georgia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Seven seas (open ocean)",
    "subregion": "Western Africa",
    "name": "Saint Helena",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Northern Africa",
    "name": "Sudan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "France",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Northern America",
    "name": "United States of America",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Latvia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Polynesia",
    "name": "French Polynesia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Croatia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Iceland",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Serbia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Russia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Hungary",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Eritrea",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Peru",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Ukraine",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Montenegro",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Uganda",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Moldova",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Brazil",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Caribbean",
    "name": "Curaçao",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Eastern Asia",
    "name": "Mongolia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Northern America",
    "name": "Canada",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Comoros",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Kosovo",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Pakistan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Niger",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Democratic Republic of the Congo",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "North America",
    "subregion": "Northern America",
    "name": "Greenland",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Andorra",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Italy",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Eastern Europe",
    "name": "Bulgaria",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Madagascar",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "São Tomé and Príncipe",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Republic of the Congo",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "San Marino",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Djibouti",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Jersey",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Republic of Macedonia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Northern Europe",
    "name": "Guernsey",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Falkland Islands",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Paraguay",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Armenia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Albania",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Western Europe",
    "name": "Monaco",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Central Asia",
    "name": "Kazakhstan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Kenya",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Cape Verde",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Argentina",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Yemen",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Azerbaijan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "South-Eastern Asia",
    "name": "East Timor",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "name": "Australia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Central Asia",
    "name": "Kyrgyzstan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Western Africa",
    "name": "Mauritania",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Spain",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "South America",
    "subregion": "South America",
    "name": "Bolivia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Gabon",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Mozambique",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Greece",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Somalia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Turkey",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Vatican City",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Afghanistan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Southern Africa",
    "name": "South Africa",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Portugal",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Rwanda",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Southern Africa",
    "name": "eSwatini",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Tanzania",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Southern Africa",
    "name": "Lesotho",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": null,
    "name": null,
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Malawi",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Central Asia",
    "name": "Tajikistan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Oman",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Saudi Arabia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Central Asia",
    "name": "Uzbekistan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Zimbabwe",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Southern Asia",
    "name": "Iran",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Burundi",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Northern Africa",
    "name": "Algeria",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Southern Africa",
    "name": "Namibia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Central Asia",
    "name": "Turkmenistan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Northern Africa",
    "name": "Libya",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Cyprus",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Syria",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Northern Africa",
    "name": "Tunisia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Eastern Africa",
    "name": "Zambia",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Iraq",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Palestine",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Israel",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Northern Africa",
    "name": "Morocco",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Lebanon",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "United Arab Emirates",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Middle Africa",
    "name": "Angola",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Qatar",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Southern Africa",
    "name": "Botswana",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Kuwait",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Gibraltar",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Jordan",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Africa",
    "subregion": "Northern Africa",
    "name": "Egypt",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Europe",
    "subregion": "Southern Europe",
    "name": "Malta",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Asia",
    "subregion": "Western Asia",
    "name": "Bahrain",
    "4_result": "below normal",
    "5_result": "below normal",
    "6_result": "below normal",
    "7_result": "below normal",
    "8_result": "below normal",
    "9_result": "below normal"
  },
  {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "name": "Norfolk Island",
    "4_result": null,
    "5_result": null,
    "6_result": null,
    "7_result": null,
    "8_result": null,
    "9_result": null
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": null,
    "5_result": null,
    "6_result": null,
    "7_result": null,
    "8_result": null,
    "9_result": null
  },
  {
    "continent": "North America",
    "subregion": "Seven seas (open ocean)",
    "name": "United States Minor Outlying Islands",
    "4_result": null,
    "5_result": null,
    "6_result": null,
    "7_result": null,
    "8_result": null,
    "9_result": null
  },
  {
    "continent": "Oceania",
    "subregion": "Australia and New Zealand",
    "name": "New Zealand",
    "4_result": null,
    "5_result": null,
    "6_result": null,
    "7_result": null,
    "8_result": null,
    "9_result": null
  }
]